POKEMON_METADATA = {
    494: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    495: {"rareza": "Raro", "metodo": "Huevo/Comienzo", "evolucion": None},
    496: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Nivel (17)"},
    497: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (36)"},
    498: {"rareza": "Raro", "metodo": "Huevo/Comienzo", "evolucion": None},
    499: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Nivel (17)"},
    500: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (36)"},
    501: {"rareza": "Raro", "metodo": "Huevo/Comienzo", "evolucion": None},
    502: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Nivel (17)"},
    503: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (36)"},
    504: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    505: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (20)"},
    506: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    507: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (16)"},
    508: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (32)"},
    509: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    510: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (20)"},
    511: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    512: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Piedra Hoja"},
    513: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    514: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Piedra Fuego"},
    515: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    516: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Piedra Agua"},
    517: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    518: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Piedra Lunar"},
    519: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    520: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (21)"},
    521: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (32)"},
    522: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    523: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (27)"},
    524: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    525: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (25)"},
    526: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Piedra Intercambio"},
    527: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    528: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (20)"},
    529: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    530: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (31)"},
    531: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    532: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    533: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (25)"},
    534: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Piedra Intercambio"},
    535: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    536: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (25)"},
    537: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (36)"},
    538: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    539: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    540: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    541: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (20)"},
    542: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (25)"},
    543: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    544: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (22)"},
    545: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (30)"},
    546: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    547: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Piedra Solar"},
    548: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    549: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Piedra Solar"},
    550: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    551: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    552: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (29)"},
    553: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (40)"},
    554: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    555: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (35)"},
    556: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    557: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    558: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (34)"},
    559: {"rareza": "Raro", "metodo": "Huevo", "evolucion": None},
    560: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Nivel (39)"},
    561: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    562: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    563: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (34)"},
    564: {"rareza": "Muy Raro", "metodo": "Fósil", "evolucion": None},
    565: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (37)"},
    566: {"rareza": "Muy Raro", "metodo": "Fósil", "evolucion": None},
    567: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (37)"},
    568: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    569: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (36)"},
    570: {"rareza": "Muy Raro", "metodo": "Captura", "evolucion": None},
    571: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (30)"},
    572: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    573: {"rareza": "Raro", "metodo": "Evolución", "evolucion": "Piedra Día"},
    574: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    575: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (32)"},
    576: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (41)"},
    577: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    578: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (32)"},
    579: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (41)"},
    580: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    581: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (35)"},
    582: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    583: {"rareza": "Común", "metodo": "Captura/Evolución", "evolucion": "Nivel (35)"},
    584: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (47)"},
    585: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    586: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (34)"},
    587: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    588: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    589: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Piedra Intercambio"},
    590: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    591: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (39)"},
    592: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    593: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (40)"},
    594: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    595: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    596: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (36)"},
    597: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    598: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (40)"},
    599: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    600: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (38)"},
    601: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (49)"},
    602: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    603: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (39)"},
    604: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Piedra Trueno"},
    605: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    606: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (42)"},
    607: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    608: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (41)"},
    609: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Piedra Noche"},
    610: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    611: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (38)"},
    612: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (48)"},
    613: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    614: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (37)"},
    615: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    616: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    617: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Piedra Intercambio"},
    618: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    619: {"rareza": "Común", "metodo": "Captura", "evolucion": None},
    620: {"rareza": "Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (50)"},
    621: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    622: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    623: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (43)"},
    624: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    625: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (52)"},
    626: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    627: {"rareza": "Raro", "metodo": "Huevo", "evolucion": None},
    628: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (54)"},
    629: {"rareza": "Raro", "metodo": "Huevo", "evolucion": None},
    630: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (54)"},
    631: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    632: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    633: {"rareza": "Raro", "metodo": "Captura", "evolucion": None},
    634: {"rareza": "Muy Raro", "metodo": "Captura/Evolución", "evolucion": "Nivel (50)"},
    635: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (64)"},
    636: {"rareza": "Muy Raro", "metodo": "Captura", "evolucion": None},
    637: {"rareza": "Muy Raro", "metodo": "Evolución", "evolucion": "Nivel (59)"},
    638: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    639: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    640: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    641: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    642: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    643: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    644: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    645: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    646: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    647: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    648: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None},
    649: {"rareza": "Legendario", "metodo": "Boss", "evolucion": None}
}
